config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :cuteness, :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:success] = "Looks like someone new is in the house! Be welcome, #{@kitten.name}!"
      redirect_to @kitten
    else
      flash[:error] = "Looks like someone doesn't know how to fill a simple form!"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      flash[:success] = "Changing is okay. We still love you, #{@kitten.name}!"
      redirect_to @kitten
    else
      flash[:error] = "Can't do that, mate!"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    flash[:success] = "No more #{@kitten.name} around here. Good bye!"
    @kitten.destroy
    redirect_to root_path
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_errors.html.erb
<% if @kitten.errors.any? %>
  <div id='error_explanation'>
    <h2><%= pluralize(@kitten.errors.count, 'error') %> prohibited this object from being saved:</h2>
    <ul>
      <% @kitten.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/kittens/_kitten.html.erb
<li>
  <%= "Name: #{kitten.name}, Age: #{kitten.age}, Cuteness: #{kitten.cuteness}, Softness: #{kitten.softness} - "%>
  <%= link_to "See details", kitten_path(kitten.id) %>
  <%= " - " %>
  <%= link_to 'Delete kitten', "/kittens/#{kitten.id}", data: { turbo_method: "delete" } %>
</li>

app/views/kittens/_kitten_form.html.erb
<%= form_with model: @kitten do |form| %>
  <%= form.label :name, 'Name:' %>
  <%= form.text_field :name, required: true %>
  <%= form.label :age, 'Age:' %>
  <%= form.number_field :age, in: 0..100 %>
  <%= form.label :cuteness, 'Cuteness:' %>
  <%= form.number_field :cuteness, in: 0..10 %>
  <%= form.label :softness, 'Softness:' %>
  <%= form.number_field :softness, in: 0..10 %>
  <%= form.submit %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render 'errors' %>
<%= render 'kitten_form' %>
<%= link_to 'Delete kitten', "/kittens/#{@kitten.id}", data: { turbo_method: "delete" } %>

app/views/kittens/index.html.erb
<h1>Kittens Index</h1>

<ul>
  <%= render @kittens %>
</ul>
<%= link_to 'New kitten', new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<%= render 'errors' %>
<%= render 'kitten_form' %>

app/views/kittens/show.html.erb
<h1>Kitten <%= @kitten.id %></h1>

<ul>
  <li>Name: <%= @kitten.name %></li>
  <li>Age: <%= @kitten.age %></li>
  <li>Cuteness: <%= @kitten.cuteness %></li>
  <li>Softness: <%= @kitten.softness %></li>
</ul>
<%= link_to 'Edit kitten', edit_kitten_path(@kitten.id) %>
<%= link_to 'Delete kitten', "/kittens/#{@kitten.id}", data: { turbo_method: "delete" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TOPKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to 'All kittens', root_url %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>
    <%= yield %>
  </body>
</html>